#  groupId: groupId
spring:

  #
  # MySQL db.
  #
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/personbatch
    username: personbatchuser
    password: abcd1234
    platform: mysql

  #
  # batch.
  #
  batch:
    jdbc:
      initialize-schema: "always"

  #
  # kafka
  #
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    template:
      default-topic: quickstart-events