spring:

  #
  # MySQL db.
  #
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/personbatch
    username: personbatchuser
    password: abcd1234
    platform: mysql

  #
  # batch.
  #
  batch:
    jdbc:
      initialize-schema: "always"


#
# Kafka.
#
kafka:
  bootstrap-servers: localhost:9092
  topic: quickstart-events
  groupId: groupId