
CREATE TABLE `PERSON` (
  `ID` bigint NOT NULL,
  `FIRSTNAME` VARCHAR(255) NOT NULL,
  `LASTNAME` VARCHAR(255) NOT NULL,
  `BIRTHDATE` DATETIME(6) NOT NULL,
  `NATIONALITY` VARCHAR(100) NOT NULL,
  `SEX` VARCHAR(1) NOT NULL,
  `SSN` VARCHAR(11) NOT NULL,
  `EMAIL` VARCHAR(255),
  `CELLULAR` VARCHAR(20),
  `ADDRESS1` VARCHAR(60),
  `ADDRESS2` VARCHAR(60),
  `STATE` VARCHAR(2),
  `CITY` VARCHAR(80),
  `ZIP` VARCHAR(10),
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;